# Generated by Django 3.2.5 on 2021-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_blog',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='my_blog',
            name='sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my_blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
